### ISSUE TITLE
User feature

### ISSUE THREAD

**Issue by jjjjjinseo** [Likelion-YeungNam-Univ/12th-BeginnerFit-BE#2]
### Auth
- [x] sign-up
- [x] sign-in  - PR #3 
- [x] 이메일 인증  - PR #26 
- [x] 아이디 찾기
- [x] 비밀번호 찾기 -PR #27 
- [x] refresh token
- [x] sign-out - PR #36 

### User CRUD
- [x] read
- [x] update
- [x] delete - PR #4
